//
//  CreateOrderModels.swift
//  CleanSwiftExample
//
//  Created by Jinny on 2021/07/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder {
  // MARK: Use cases
  
  enum Something {
    struct Request {
        
    }
    
    struct Response {
        
    }
    
    struct ViewModel {
        
    }
  }
}
